Should be able to run faild as the faild user.
git-svn-id: https://ut.svn.beanstalkapp.com/ngfw/hades/pkgs@22443 8ebf8b4e-06f3-0310-961f-89f74618be54

diff --git a/untangle-faild/debian/untangle-faild.postinst b/untangle-faild/debian/untangle-faild.postinst
--- a/untangle-faild/debian/untangle-faild.postinst
+++ b/untangle-faild/debian/untangle-faild.postinst
@@ -1,11 +1,52 @@
 #!/bin/sh
 
+SUDOERS_CONF_FILE=/etc/sudoers
+
 ourInit() {
     if [ -x /usr/sbin/invoke-rc.d ] && [ ! "`readlink /usr/sbin/invoke-rc.d`" = /bin/true ] ; then
         invoke-rc.d $1 $2
     else
         /etc/init.d/$1 $2
     fi
+}
+
+sudoers_awk_script()
+{
+    ## Grant privileges to faild.
+    cat <<'EOF'
+/# untangle-faild.postinst$/ { next }
+{ print }
+END { 
+  print "# Start of Untangle FailD elevated privileges # untangle-faild.postinst";
+  print "Defaults:faild     env_keep+=\"FAILD_*\"                      # untangle-faild.postinst";
+  print "faild              ALL = NOPASSWD: /usr/sbin/arping         # untangle-faild.postinst";
+  print "faild              /usr/share/untangle-faild/bin/set-uplink # untangle-faild.postinst";
+  print "# End of Untangle FailD elevated privileges # untangle-faild.postinst";
+  }
+EOF
+}
+
+
+update_sudoers_file()
+{
+    local t_temp
+
+    if [ ! -f "${SUDOERS_CONF_FILE}" ]; then
+        echo "Missing sudoers file (${SUDOERS_CONF_FILE})."
+        return 1
+    fi
+    
+    t_temp=`mktemp` || {
+        echo "Unable to create temp file, sudoers will not be updated."
+        return 2
+    }
+
+    awk "`sudoers_awk_script`" ${SUDOERS_CONF_FILE} >  ${t_temp} || {
+        echo "Unable to modify sudoers file, aborting."
+        return 3
+    }
+
+    mv ${t_temp} ${SUDOERS_CONF_FILE}    
 }
 
 FAILD_CONFIG_FILE="/etc/untangle-faild.conf"
@@ -37,4 +78,5 @@ adduser --no-create-home --home /var/log/untangle-faild --system --gecos "" --sh
 
 chown -R faild:nogroup /var/log/untangle-faild
 
-exit 0
+update_sudoers_file
+
