svn merge -c 18954 svn://chef/branch/prod/release-5.4/hades
git-svn-id: https://ut.svn.beanstalkapp.com/ngfw/hades/pkgs@18955 8ebf8b4e-06f3-0310-961f-89f74618be54

diff --git a/untangle-arp-eater/files/usr/share/untangle-arp-eater/bin/set_config b/untangle-arp-eater/files/usr/share/untangle-arp-eater/bin/set_config
--- a/untangle-arp-eater/files/usr/share/untangle-arp-eater/bin/set_config
+++ b/untangle-arp-eater/files/usr/share/untangle-arp-eater/bin/set_config
@@ -1,6 +1,6 @@
 #!/bin/dash
 
-ARPEATER_BIND_PORT=3002
+ARP_EATER_BIND_PORT=3002
 
 if [ $# != 1  ]; then
     echo "USAGE: $0 <config file name>"
@@ -12,7 +12,7 @@ if [ -f /etc/default/untangle-arp-eater ]; then
 fi
 
 set_config() {
-    curl -s -F 'json_request=@-' -m 10 "http://localhost:${ARPEATER_BIND_PORT}" <<EOF || echo "Unable to connect to host"
+    curl -s -F 'json_request=@-' -m 10 "http://localhost:${ARP_EATER_BIND_PORT}" <<EOF || echo "Unable to connect to host"
 { "function" : "set_config",
 "config" : 
 `cat $1`
