Several cleanups for failover. 1. PPPoE should now work properly from the manual test and from the internal test. 2. ARP test should now work on PPPoE. 3. Bridge manual test should now work. 4. Fixed a bug in the drop down for the failover threshold. Closes: #6438 Closes: #6439.
git-svn-id: https://ut.svn.beanstalkapp.com/ngfw/hades/pkgs@23966 8ebf8b4e-06f3-0310-961f-89f74618be54

diff --git a/untangle-faild/files/usr/share/untangle-faild/bin/arp_test b/untangle-faild/files/usr/share/untangle-faild/bin/arp_test
--- a/untangle-faild/files/usr/share/untangle-faild/bin/arp_test
+++ b/untangle-faild/files/usr/share/untangle-faild/bin/arp_test
@@ -1,3 +1,12 @@
 #!/bin/dash
 
-sudo arping -S $FAILD_PRIMARY_ADDRESS -i $FAILD_OS_NAME  -c 1 $FAILD_GATEWAY > /dev/null 
+if [ "${FAILD_PRIMARY_ADDRESS}" = "0.0.0.0" ]; then
+    exit 1
+fi
+
+if [ "${FAILD_OS_NAME#ppp}" != "${FAILD_OS_NAME}" ]; then
+    ## If this is a PPP interface, it just needs to be online (you can't ARP a PPPoE interface.)
+    ifconfig ${FAILD_OS_NAME} > /dev/null
+else
+    sudo arping -S $FAILD_PRIMARY_ADDRESS -i $FAILD_OS_NAME  -c 1 $FAILD_GATEWAY > /dev/null 
+fi
